// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8RtShPCFXt6boWWvY-vlxrgvStD03KCI',
    appId: '1:899018665675:web:48569303830ca14e32b54e',
    messagingSenderId: '899018665675',
    projectId: 'bv-doubtnut',
    authDomain: 'bv-doubtnut.firebaseapp.com',
    storageBucket: 'bv-doubtnut.appspot.com',
    measurementId: 'G-S6ZEKF539F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz1oo7xyeZqpLdw1mTymW4o0mC9YNyWHU',
    appId: '1:899018665675:android:32a3ad3e261cf1c232b54e',
    messagingSenderId: '899018665675',
    projectId: 'bv-doubtnut',
    storageBucket: 'bv-doubtnut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZdwyX0b-w8BPjaSsSITc3hinDDVkIovI',
    appId: '1:899018665675:ios:7d4443e00d30441e32b54e',
    messagingSenderId: '899018665675',
    projectId: 'bv-doubtnut',
    storageBucket: 'bv-doubtnut.appspot.com',
    iosClientId: '899018665675-5olcoq29loeac9jgjbj2e4dkk1p97g0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZdwyX0b-w8BPjaSsSITc3hinDDVkIovI',
    appId: '1:899018665675:ios:7d4443e00d30441e32b54e',
    messagingSenderId: '899018665675',
    projectId: 'bv-doubtnut',
    storageBucket: 'bv-doubtnut.appspot.com',
    iosClientId: '899018665675-5olcoq29loeac9jgjbj2e4dkk1p97g0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdf',
  );
}
